# Generated by Django 4.1.3 on 2022-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
